name: doc
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main
      - doc*
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: sudo apt update && sudo apt install -y optipng
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-version: latest
          environment-file: env-dev.yml
          activate-environment: ncrf
          auto-activate-base: false
      - name: build Neuro-currentRF and doc
        shell: bash -el {0}
        run: |
          pip install .
          make -C docs html
      - name: Prune sphinx environment
        run: rm -R ./docs/_build/html/.doctrees
      - uses: actions/upload-artifact@v4
        with:
          name: doc-dev
          path: ./docs/_build/html

  deploy:
    if: github.event_name == 'push'
    needs: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: doc-dev
          path: ./doc-dev
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc-dev
          # target-folder: ./neuro-currentRF
          # git-config-name: 'github-actions[bot]'
          # git-config-email: 'github-actions[bot]@users.noreply.github.com'
          # single-commit: true
          # force: true
