name: Python Package using Conda on linux and macos

on:
  push:
    branches:
      - master
      - maint*
  pull_request:
    branches: [ "master" ]

jobs:
  build-posix:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cv: 1
          - os: macos-latest
            cc: 1

    steps:
    - uses: actions/checkout@v4
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        miniforge-version: latest
        environment-file: env-dev.yml
        activate-environment: ncrf
        auto-activate-base: false
    - name: build Neuro-currentRF
      shell: bash -el {0}
      run: |
        python -m pip install .[test]
        rm -rf ncrf
    - if: ${{ matrix.cc }}
      name: Test with pytest and code-cov
      shell: bash -el {0}
      run: |
        pytest --cov --cov-report=xml --pyargs ncrf  # namespace vs module import?
    - if: ${{ matrix.cc }}
      name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - if: ${{ matrix.cv }}
      name: Test with pytest and cv
      shell: bash -el {0}
      run: |
        pytest --crossvalidation=True --pyargs ncrf
